// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.shanidgafur.error
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Error : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Error"",""namespace"":""com.shanidgafur.error"",""fields"":[{""name"":""id"",""doc"":""System-assigned numeric user ID. Cannot be changed by the user."",""type"":""int""},{""name"":""appname"",""doc"":""The name of the application generating the error"",""type"":""string""},{""name"":""details"",""doc"":""The name of the application generating the error"",""type"":{""type"":""record"",""name"":""ErrorDetails"",""namespace"":""com.shanidgafur.error"",""fields"":[{""name"":""category"",""doc"":""Category of the error. Example: DatabaseConnectionError"",""type"":""string""},{""name"":""severity"",""doc"":""The severity of the error. Example: CRITICAL, FATAL, WARNING"",""type"":""string""},{""name"":""timestamp"",""doc"":""Timestamp (milliseconds since epoch) when the error was generated"",""type"":""long""}]}}]}");
		/// <summary>
		/// System-assigned numeric user ID. Cannot be changed by the user.
		/// </summary>
		private int _id;
		/// <summary>
		/// The name of the application generating the error
		/// </summary>
		private string _appname;
		/// <summary>
		/// The name of the application generating the error
		/// </summary>
		private com.shanidgafur.error.ErrorDetails _details;
		public virtual Schema Schema
		{
			get
			{
				return Error._SCHEMA;
			}
		}
		/// <summary>
		/// System-assigned numeric user ID. Cannot be changed by the user.
		/// </summary>
		public int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		/// <summary>
		/// The name of the application generating the error
		/// </summary>
		public string Appname
		{
			get
			{
				return this._appname;
			}
			set
			{
				this._appname = value;
			}
		}
		/// <summary>
		/// The name of the application generating the error
		/// </summary>
		public com.shanidgafur.error.ErrorDetails Details
		{
			get
			{
				return this._details;
			}
			set
			{
				this._details = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._id;
			case 1: return this._appname;
			case 2: return this._details;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._id = (System.Int32)fieldValue; break;
			case 1: this._appname = (System.String)fieldValue; break;
			case 2: this._details = (com.shanidgafur.error.ErrorDetails)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
